### ISSUE TITLE
Chunked variables

### ISSUE THREAD

**Issue by mjwoods** [mjwoods/RNetCDF#32]
Add options for chunking in variable definitions. Also consider compression and checksumming.

**Comment by adrfantini** [comment]
Just to motivate the implementation of these features: for an advanced `ndtCDF` user, I think that chunking and compression are absolutely vital. These are things that I use daily (with `ncdf4`).

**Comment by mdsumner** [comment]
I also am keen for this, at a minimum to be able to discover what the chunking is of a given variable.

**Comment by mjwoods** [comment]
Hi @mdsumner and @adrfantini ,

Thanks for your patience. I have added various netcdf4 options to `var.def.nc` and `var.inq.nc`, as described in the help pages. I hope you find these new features useful. Please raise issues if you find any problems.

Regards,
Milton.

**Comment by adrfantini** [comment]
Thank you for this. I'll test this asap.

**Comment by adrfantini** [comment]
I noticed that the compression level is indicated as going from 0 to 9. IIRC it goes from 1 to 9: https://www.unidata.ucar.edu/blogs/developer/entry/netcdf_compression
