### ISSUE TITLE
Write to read-only

### ISSUE THREAD

**Issue by mjwoods** [mjwoods/RNetCDF#4]
Michael Sumner reported the following problem:

> I'm trying to read from thredds servers, and I get this error: 

```r
u <- "http://coastwatch.pfeg.noaa.gov/erddap/griddap/erdQSwind3day"
library(RNetCDF)
var.get.nc(open.nc(u), "altitude")
Error: NetCDF: Write to read only
```

> ncdf4 works fine: 

```r
library(ncdf4)
ncvar_get(nc_open(u), "altitude")
[1] 10
```

> Any ideas?

**Comment by mjwoods** [comment]
Thanks for letting me know about the problem. Unfortunately, fixing it will require a new release of RNetCDF.

The current RNetCDF C interface is designed primarily for reading and writing of netcdf3 files (but it happens to work for most netcdf4 files too). Files can be in "define" or "data" mode, and certain operations are only allowed in one mode or the other. To make things easier for R users, we automatically switch to the required mode for each operation. There is no netcdf function to query which mode the file is in, so we always try to change the mode and then check the return code from netcdf. There is a special error code to indicate when a mode change failed because it was not needed (NC_ENOTINDEFINE), but it does not seem to be used when reading files over opendap. (I am fairly sure this used to work, but something must have changed in opendap or netcdf since I last tried it).

To fix this problem, I will need to find a smarter way of switching between modes. It could take a while ...

**Comment by mjwoods** [comment]
This is resolved by 2a8407bd .

**Comment by mjwoods** [comment]
@mdsumner, FYI, in case you didn't know this has been fixed.

**Comment by mdsumner** [comment]
Awesome thanks, I've tried this on Windows and it now works fine. (I don't have careful records as my access to Windows is a bit scatty at the moment, but I have also done extensive read and print testing on Linux in this version with no problems at all).

**Comment by mdsumner** [comment]
I just checked this works with Windows 64 with the 1.9-1 release. 

It nicely errors out on 32-bit mode too: 

 var.get.nc(open.nc(u), "altitude")
Error: NetCDF: Unknown file format


Thanks!

**Comment by mjwoods** [comment]
Thanks for the feedback, @mdsumner. I tested the package as best I could before making the release, but you never really know how things will go in the wild. I'm relieved to know that it works.
