### ISSUE TITLE
udunits2.h not checked/not found (openSUSE)

### ISSUE THREAD

**Issue by GreatEmerald** [mjwoods/RNetCDF#49]
On openSUSE Tumbleweed, RNetCDF does not find the udunits header file. Configure log shows:
```
checking for library containing utFree... -ludunits2
checking udunits2/udunits.h usability... no
checking udunits2/udunits.h presence... no
checking for udunits2/udunits.h... no
checking udunits.h usability... no
checking udunits.h presence... no
checking for udunits.h... no
configure: error: "unable to use udunits2 or udunits"
```
On openSUSE it is available from the `udunits2-devel` package as `/usr/include/udunits2.h`. It looks like the configure script simply doesn't check for any header files with a `2` in it.

This is not an issue for the `udunits2` R package, that one installs fine, so a solution for this issue would also be to implement #12.

**Comment by mjwoods** [comment]
Thanks for reporting the problem, @GreatEmerald . There seem to be a few different names for the udunits2 header files, and I haven't yet come across a udunits2.h. I'll add this to my configure script, and I will try to have a test branch ready for you in the next few days.

For a quick workaround, you may be able to install a udunits-devel package (i.e. udunits-1), which is usually compatible with RNetCDF.

**Comment by mjwoods** [comment]
Correction - udunits2.h is part of udunits2, but it only provides version 2 of the udunits interface. The version 1 interface is also provided by udunits2 in a separate file called udunits.h. I'm not sure why it's not installed on openSUSE, but I'll keep digging.

As I said before, a genuine udunits-1 package should provide a udunits.h that you can use (for now).

**Comment by mjwoods** [comment]
Out of interest, I tried installing the "units" package for R (from source code under MacPorts). Even though udunits2-devel is installed, it isn't found by the "units" package. Clearly there is some disagreement about the right way to install udunits2 on different systems.

**Comment by mjwoods** [comment]
Hi @GreatEmerald , I was able to install RNetCDF on openSUSE Leap 15.0. It required 4 separate udunits packages to be installed:

* udunits2
* udunits2-devel
* udunits-compat
* udunits-compat-devel

The "compat" libraries provide the udunits-1 interface for the udunits-2 package. RNetCDF uses the udunits-1 interface because, until now, it has supported systems with almost any version of udunits.

**Comment by GreatEmerald** [comment]
Yes, I thought it might be the `udunits-compat` package. It's nice that it works, though I think #12 is probably a more sustainable solution, since the udunits interface may get deprecated at some point.

**Comment by mjwoods** [comment]
Hi @GreatEmerald , I agree about #12 , so I have created a new branch to implement calendar functions using the units package. Please have a look at #50 and let me know if that would work well enough for you. If you can test the new branch and provide feedback, that would be very helpful.

**Comment by mjwoods** [comment]
Hi again @GreatEmerald , I have changed my plans. Instead of using the "units" package (as in #50), I have upgraded RNetCDF to use udunits-2 instead of udunits-1, while allowing installation to succeed even if udunits-2 cannot be found. Please see #53 for details. I look forward to any comments or testing that you can provide.

**Comment by chandra04** [comment]
On ubuntu please install usunits with below command after it the try RNetCDF. For my case it worked.

> sudo apt-get install libudunits2-dev

**Comment by mjwoods** [comment]
Thanks @chandra04 , that's good to know. It's possible that Ubuntu includes udunits1 support in their udunits2 package.
