### ISSUE TITLE
netcdf4 and opendap support on Windows

### ISSUE THREAD

**Issue by mjwoods** [mjwoods/RNetCDF#5]
Michael Sumner reports that RNetCDF on Windows is built with netcdf3. It would be useful to build with netcdf4 instead, so that netcdf4 classic files can read and modified. OPeNDAP support would also be useful.

**Comment by mjwoods** [comment]
Full netcdf4 is planned for a later release of RNetCDF. An interim release can address this issue.

Commit e5854561 ensures that RNetCDF is built with netcdf4 on Windows. The build has been tested by uploading the package to https://win-builder.r-project.org.

It would be helpful to have confirmation that CRAN can also build the package, and that the resulting package will support OPeNDAP.

**Comment by jeroen** [comment]
Tagging myself @jeroen
