### ISSUE TITLE
find NetCDF lib version?

### ISSUE THREAD

**Issue by mdsumner** [mjwoods/RNetCDF#51]
Is there any way to find the library version with RNetCDF functions? 

I'm seeing failures on Ubuntu Trusty (14.04) with version 4.1.3 when attempting to open the Unidata file `test_hgroups.nc`, it works fine on Xenial (16.04) with version 4.4.0. I'm not sure ultimately what the problem is (groups?) but having the version would give something to test for R code.

**Comment by mjwoods** [comment]
Hi @mdsumner , I can open `test_hgroups.nc` using netcdf-4.1.2, the latest RNetCDF (b292afd1) and R-3.5.1. Can you please give more details about the problem? Which versions of R and RNetCDF are you using?

It is possible for RNetCDF to disable features that are not supported by a version of netcdf, but I need to know which features are causing problems.

**Comment by mdsumner** [comment]
It's really the lib version I want, is that possible?

**Comment by mjwoods** [comment]
Hi @mdsumner , I have created pull request #55 that provides a new feature to report the NetCDF library version. Would that help you?

**Comment by mjwoods** [comment]
As an example of the output from the new `file.inq.nc`, I get the following result on my system:

```
> file.inq.nc(fid)$libvers
[1] "4.6.1 of Nov 13 2018 04:38:05 $"
```

This is the version string reported by the NetCDF library function `nc_inq_libvers()`.

**Comment by mdsumner** [comment]
That's fabulous thank you. I lost the context of the file problem above, but will pursue if I find it again. Thanks!

**Comment by mjwoods** [comment]
Thanks @mdsumner , I have merged the changes into the master branch. Please let me know how you go - whether the news is good or bad.
