### ISSUE TITLE
Configure error with udunits.

### ISSUE THREAD

**Issue by dblodgett-usgs** [mjwoods/RNetCDF#57]
Just got up and running with a new Mojave laptop and am working on getting all my dependencies in line. [Units](https://github.com/r-quantities/units) installs fine with:  
```
checking for XML_ParserCreate in -lexpat... yes
checking udunits2.h usability... yes
checking udunits2.h presence... yes
checking for udunits2.h... yes
checking for ut_read_xml in -ludunits2... yes
```

But installing `RNetCDF` I get:  
```
checking for library containing XML_StopParser... -lexpat
checking for library containing utFree... no
checking for library containing utScan... no
configure: error: "unable to use udunits2 or udunits"
```

I installed udunits with `brew install udunits`.

R 3.6.1

Any ideas what to look for? I'm not real familiar with how these packages link up to libraries...

**Comment by dblodgett-usgs** [comment]
Just to check, I tried:`devtools::install_github("mjwoods/RNetCDF")` ... worked. So --- time for a CRAN release?!?

**Comment by dblodgett-usgs** [comment]
Realizing that the github head is _way_ ahead of the latest CRAN release. Working on some other packages and need to test with the latest CRAN release but I can't get it to load per the note above. Going to reopen and see if anyone has ideas... ?

**Comment by mjwoods** [comment]
Hi @dblodgett-usgs , the current CRAN version of RNetCDF uses udunits-1 natively, but it can use a compatibility layer provided by most installations of udunits-2. It seems that some distributions have stopped providing the compatibility layer, and perhaps brew is doing that. One workaround would be to install udunits-2 from source code, which includes the compatibility layer by default. Then you would install RNetCDF from source code using a command like the following:

```
R CMD INSTALL --configure-args="CPPFLAGS=-I/sw/include \
    LDFLAGS=-L/sw/lib" RNetCDF_1.9-1.tar.gz
```

You would need to replace '/sw' with the directory where your custom udunits is installed.

Sorry about the inconvenience this is causing you. I'm hoping to push out a new CRAN release of RNetCDF within a few months.

**Comment by dblodgett-usgs** [comment]
OK. Cool.

So I did:

```
su -
wget -O - ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.26.tar.gz | gunzip -c | pax -r
cd udunits-2.2.26/
./configure --prefix=/opt
make
make install
```

Which put udunits.h in `/opt/include/`

Then I did:

```
R CMD INSTALL --configure-args="CPPFLAGS=-I/opt/include \
     LDFLAGS=-L/opt/lib" RNetCDF_1.9-1.tar.gz
```

Which didn't work initially, but then I uninstalled the `brew` version of udunits and it _did_ work. Wheee!! Will be spending some time testing stuff over in `ncmeta` and `intersectr` against both the old and new versions of `RNetCDF` in the coming weeks. Hopefully good things. Looks like you've been hard at work!

**Comment by mjwoods** [comment]
I'm glad you were able to install the old CRAN package. Please let me know if your testing reveals any problems, especially in the latest github version.

**Comment by dblodgett-usgs** [comment]
Been doing some testing over in https://github.com/hypertidy/ncmeta/pulls?q=is%3Apr+is%3Aclosed (see two latest PRs)

The addition of NetCDF4 hidden attributes is going to be super useful but we were relying on the simplicity of the old NetCDF3-only content over there. All good now that I handle some of the corner cases that it brought in. I did notice a couple things come back `integer(0)` (length 0) instead of `NA` (length 1) -- might be nice to always return something of length 1 in lists so coercion to data.frame or tibble is nicer. 

That's all I've got so far. Excited that you are moving out on this addition!

**Comment by mjwoods** [comment]
Hi @dblodgett-usgs , I'd like to check the corner cases you mentioned above. Can you supply any more details about them? They could be design features, or they could be bugs. It would be nice to know for sure.

**Comment by dblodgett-usgs** [comment]
`ncdfgeom` was coercing the list to a tibble directly without being selective. That caused some issues when files had attributes of length 2 (don't remember the example but know it happened) or attributes that came back `integer(0)`. These caused what I was calling corner cases in `ncdfgeom`. Other than that, I don't think there were really any other problems. 

Been using the github version in anger for a while -- 👍 on all your hard work. It's a huge service!

**Comment by mjwoods** [comment]
Thanks for the update.

Attributes can be vectors in NetCDF datasets, and RNetCDF is supposed to return the whole vector (but it may not have done this consistently in earlier versions).
 
I am curious to know more about the `integer(0)` case, because I can't think of a valid reason for an attribute to be empty.

**Comment by dblodgett-usgs** [comment]
Note sure what `filter_params` is...

```r
download.file("https://www.northwestknowledge.net/metdata/data/pr_2019.nc", 'pr_2019.nc')
f <- 'pr_2019.nc'
nc <- RNetCDF::open.nc(f)
RNetCDF::var.inq.nc(nc, 1)
$id
[1] 1

$name
[1] "lat"

$type
[1] "NC_DOUBLE"

$ndims
[1] 1

$dimids
[1] 1

$natts
[1] 5

$chunksizes
[1] 585

$cache_bytes
[1] 4194304

$cache_slots
[1] 1009

$cache_preemption
[1] 0.75

$deflate
[1] 9

$shuffle
[1] FALSE

$big_endian
[1] FALSE

$fletcher32
[1] FALSE

$szip_options
[1] NA

$szip_bits
[1] NA

$filter_id
[1] 0

$filter_params
integer(0)
```

**Comment by mjwoods** [comment]
Thanks @dblodgett-usgs , I have recorded this problem in issue #60 . Are there any other issues you have found in your testing?

**Comment by dblodgett-usgs** [comment]
Nope. Thanks!!
