### ISSUE TITLE
RNetCDF now failing R CMD CHECK

### ISSUE THREAD

**Issue by jldasch** [mjwoods/RNetCDF#75]
RNetCDF started failing yesterday on my system while running software that had worked for months.  The failure is "NetCDF: Filter error: filter not defined for variable".    This same error appears when running R CMD CHECK RNetCDF_2.1-1.tar.gz 
[check.txt](https://github.com/mjwoods/RNetCDF/files/4500006/check.txt)

**Comment by jldasch** [comment]
It appears that using all options in the var.def.nc is a work around.  This was not required before.

**Comment by mjwoods** [comment]
Hi jldasch,

Thanks for reporting the problem. It looks like netcdf version 4.7.4 has recently been released, and they have changed some behaviour related to filters. I will investigate and issue an updated RNetCDF soon. In the meantime, try reverting to an older netcdf version if you can. 

Regards,
Milton.

**Comment by mjwoods** [comment]
Hi @jldash , I have fixed `R CMD CHECK` so that it works with netcdf-4.7.4. Are you able to test the latest master branch (03c4ccb807) with your software?

**Comment by jldasch** [comment]
Hi,

	Thanks!  The latest master branch works fine with my setup.

	I had found the solution (workaround?) was to explicitly  set chunking, chunksizes, deflate in var.def.nc()

	Thanks again!  

	I had recently switched from the ncdf4 R package to RNetCDF because I find it a more complete implementation.  

-John

**Comment by mdsumner** [comment]
Do you know if this will fix this problem too? I haven't had a chance to check yet, just in case, before you release

https://github.com/hypertidy/ncmeta/issues/38

**Comment by mjwoods** [comment]
Hi Michael, I have tested my RNetCDF changes with ncmeta, and yes, it does fix the problem.

**Comment by mjwoods** [comment]
@jldasch and @mdsumner , I have submitted RNetCDF_2.3-1 to CRAN, so a new release is imminent. Thanks for reporting the problem - I appreciate your help in keeping RNetCDF going.
