### ISSUE TITLE
att.put.nc() does not recognize NA_real_ anymore

### ISSUE THREAD

**Issue by GregoryOuik** [mjwoods/RNetCDF#77]
Behaviour of att.put.nc() seems to have changed regarding use of NA_real_  (which is the correct value for missing double precision data).

Setting a "missing_value" attribute with variable type "NC_DOUBLE" and value NA_real_ that worked properly with RNetCDF on R.3.3.2 now results in the following error :  "NA values sent to netcdf without conversion to fill value"

I found out this problem when installing and testing our codes on our new computing mainframe
Linux system, compiler ICC_2018.5.274
R version : 3.6.1
netcdf-c-4.7.1 installed

Thanks for any clue !

**Comment by mjwoods** [comment]
Hi @GregoryOuik , thanks for reporting the problem. The NetCDF conventions are vague about the use of non-finite values in datasets, and I have not explicitly tested storing NA values in attributes. I think RNetCDF should handle this more gracefully, and I will try to fix this in the next release.

For now, there is no workaround that I can see, other than using a finite value for your missing_value attribute. The usual practice is to choose a missing_value that is outside the valid_range of your data. Then RNetCDF will automatically convert NA to missing_value when writing and vice-versa when reading.

I hope this problem is not a show-stopper for you. I will try to find a solution soon, and I would welcome your help in testing it.

**Comment by GregoryOuik** [comment]
Hi @mjwoods, thanks for your quick reply. Bypassing this issue is easy, using as you stated constant numeric values - so i have been able to run the program till the end after a couple of changes. My main concern is dependencies : we have plenty of applications taking as input the generated ncdef files, and that expect getting NA's as missing values - i've checked that grib generation is not affected, but for other purposes it's a bit more tedious. We are not in such a hurry, but if you are able to fix this, it would be very welcome, And i will of course help you testing the release. Thanks again!

**Comment by mjwoods** [comment]
Hi @GregoryOuik , I have made some changes that I hope will fix your problem. If you would like to test them, please try the following commands in a terminal (on a Linux machine):

```
git clone git@github.com:mjwoods/RNetCDF.git
git checkout na_fill
cd ..
R CMD build RNetCDF
R CMD check RNetCDF_2.4-1.tar.gz
R CMD INSTALL RNetCDF_2.4.1-tar.gz
```

You may need to try upper- or lower-case variants of the "build", "check" and "INSTALL" commands above, depending on your R installation.

The package should then be installed and ready to use with your R code.

**Comment by mjwoods** [comment]
Hi @GregoryOuik , have you been able to test the branch in #78 yet?

**Comment by GregoryOuik** [comment]
Hi Milton, many thanks for the modification - i did not have time to apply modifications on our codes and recompile our packages before going on holidays, but i'm back, i'll do this asap and let you know. Sincerely yours.

**Comment by GregoryOuik** [comment]
Hi Milton, I have tested your modification, everything is fine - thanks for your efficient intervention, sorry for the delay in testing it. Best wishes for the future!

**Comment by GregoryOuik** [comment]
Hi Milton, I have tested your modification, everything is fine - thanks for your efficient intervention, sorry for the delay in testing it. Best wishes for the future!

**Comment by GregoryOuik** [comment]
Hi Milton, I have tested your modification, everything is fine - thanks for your efficient intervention, sorry for the delay in testing it. Best wishes for the future!

**Comment by GregoryOuik** [comment]
Hi Milton, I have tested your modification, everything is fine - thanks for your efficient intervention, sorry for the delay in testing it. Best wishes for the future!

**Comment by mjwoods** [comment]
Thanks helping to test the changes. I will merge them into the master branch and release a new package on CRAN soon.

Please let me know if you have any further problems by raising a new issue. And thanks for continuing to use RNetCDF!

**Comment by mjwoods** [comment]
Hi @GregoryOuik , I have submitted an updated package to CRAN, and it will be available for download soon. The package includes the changes from #78 , so it should solve your problems with `NA_real_` without needing a customised build. Regards, Milton.
