### ISSUE TITLE
NetCDF4 compound types

### ISSUE THREAD

**Issue by mjwoods** [mjwoods/RNetCDF#8]
Friedemann Reum requests support for compound types.

**Comment by mjwoods** [comment]
Compound types are similar to C structs. The nearest equivalent in R would be a list of mixed types (AFAIK). The netcdf4 library does not provide support for conversions between compound types and other types, so all conversions to/from R must be handled by RNetCDF.

In the current master branch of RNetCDF, many of the low-level type conversions are now supported. However, the higher-level functions to support compound types have not yet been written.

Support for compound types is the main hurdle to overcome in supporting netcdf4 features. We may need to release a version with partial support for netcdf4, followed by an update to support compound types.

**Comment by mdsumner** [comment]
For what it's worth, rhdf5 fully supports these already. I've used this extensively for the NASA ocean colour L3bin format and for libkea (a GeoTIFF-alike).  (rhdf5 doesn't support classic format however)

**Comment by mjwoods** [comment]
Thanks @mdsumner . I'll look at rhdf5 to see if we can reuse some of their data structures or functions.
