### ISSUE TITLE
Installing RNetCDF from rstudio. defining CPPFLAGS ?

### ISSUE THREAD

**Issue by yatled** [mjwoods/RNetCDF#95]
Hi,
I'm a very low level user of R. Running on fedora 34, R 4.05. Using rstudio i am trying to install RNetCDF 

> install.packages("RNetCDF")
Installing package into ‘/home/<user>/R/x86_64-redhat-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
essai de l'URL 'https://cran.rstudio.com/src/contrib/RNetCDF_2.5-2.tar.gz'
Content type 'application/x-gzip' length 143675 bytes (140 KB)
==================================================
downloaded 140 KB

* installing *source* package ‘RNetCDF’ ...
** package ‘RNetCDF’ correctement décompressé et sommes MD5 vérifiées
** using staged installation
checking for gcc... gcc -m64
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc -m64 accepts -g... yes
checking for gcc -m64 option to enable C11 features... none needed
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking size of int... 4
checking size of long long... 8
checking size of size_t... 8
checking for nc-config... no
checking for netcdf.h... no
configure: error: netcdf.h was not compiled - defining CPPFLAGS may help
ERROR: configuration failed for package ‘RNetCDF’
* removing ‘/home/<user>/R/x86_64-redhat-linux-gnu-library/4.0/RNetCDF’
Warning in install.packages :
  installation of package ‘RNetCDF’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpODM1hG/downloaded_packages’`

I suppose my problem should be solved by the action described in INSTALL (R CMD INSTALL --configure-args="CPPFLAGS=-I/sw/include \    LDFLAGS=-L/sw/lib LIBS=-lhdf5" RNetCDF_2.5-2.tar.gz), but i never used r cmd install and i don't know how to pass these arguments to install.packages
Sorry for the stupid question 
Bertrand

**Comment by mjwoods** [comment]
Hi Bertrand, the netcdf components are split across several packages on Fedora, so you may need to the install the netcdf-devel package. Please try that and run `install.packages` again. Otherwise, the `R CMD INSTALL` command requires a shell (bash) terminal window, as opposed to an R session. You may be able to access a shell terminal from within RStudio via the menus. Please let me know how you get on.

**Comment by yatled** [comment]
hi,

thank you very much, it worked fine. (I have to confess that I first looked for a netcdf-devel package in R......).
bertrand

**Comment by mjwoods** [comment]
I'm glad to hear that it installed correctly for you! Good luck with your work.
