### ISSUE TITLE
A NetCDF file is not readable when created with `diskless = TRUE` and `persist = TRUE`

### ISSUE THREAD

**Issue by AndreySamokhin** [mjwoods/RNetCDF#96]
I've encountered a problem. A NetCDF file created with `diskless = TRUE` and `persist = TRUE` is not readable.

Example 1. Everything is ok.
```
file1 <- "file1.nc"
nc1 <- create.nc(file1, prefill = FALSE, format = "classic")
dim.def.nc(nc1, "station", 5)
dim.def.nc(nc1, "max_string_length", 32)
var.def.nc(nc1, "name", "NC_CHAR", c("max_string_length", "station"))
myname <- c("alfa", "bravo", "charlie", "delta", "echo")
var.put.nc(nc1, "name", myname)
close.nc(nc1)

nc1 <- open.nc(file1)
close.nc(nc1)
```

Example 2. The only difference from Example 1 is the values of the `diskless` and `persist` arguments. The created file is not readable (the following message appears: "Error in open.nc(file2) : Invalid argument").
```
file2 <- "file2.nc"
nc2 <- create.nc(file2, prefill = FALSE, format = "classic",
                 diskless = TRUE, persist = TRUE)
dim.def.nc(nc2, "station", 5)
dim.def.nc(nc2, "max_string_length", 32)
var.def.nc(nc2, "name", "NC_CHAR", c("max_string_length", "station"))
myname <- c("alfa", "bravo", "charlie", "delta", "echo")
var.put.nc(nc2, "name", myname)
close.nc(nc2)

nc2 <- open.nc(file2)
close.nc(nc2)
```

**Comment by mjwoods** [comment]
Hi @AndreySamokhin , both examples work for me on the platforms I have available to me. Can you describe your setup in more detail, please?

**Comment by AndreySamokhin** [comment]
@mjwoods, thank you for replying!
I've tried to run Example 2 on two machines. I've got the identical results: "Error in open.nc(file2) : Invalid argument". The same message is appeared when I use, for example, "ncdump.exe" tool. The reason why I cannot open "file2.nc" is the presence of an additional byte. This is the first 48 bytes from the "file2.nc":
```
43 44 46 01 00 00 00 00 00 00 00 0D 0A 00 00 00
02 00 00 00 07 73 74 61 74 69 6F 6E 00 00 00 00
05 00 00 00 11 6D 61 78 5F 73 74 72 69 6E 67 5F
...
```
Deleting the 11th byte (i.e. 0D) makes the file readable.


Machine 1
```
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    
system code page: 1251

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RNetCDF_2.5-2
```

Machine 2
```
R version 4.1.3 (2022-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252  
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    
system code page: 1251

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base    

other attached packages:
[1] RNetCDF_2.5-2
```

**Comment by AndreySamokhin** [comment]
Thanks! Maybe this problem is worth to be mentioned in the documentation. I think it can help to save time for people who decide to use the `diskless` option on Windows.

**Comment by mjwoods** [comment]
Hi Andrey, I'm wondering which of the two options is causing the problem on Windows. Are `diskless` files working without `persist`?

**Comment by AndreySamokhin** [comment]
Actually, I don't know how to check it. Can you give me a piece of advice?
I've made up two additional examples. But it seems to me that they are not very useful.

Example 3. In comparison with Example 2, the value of the `persist` argument was changed to `FALSE`, and a line `sync.nc(nc3)` was added. Unfortunately, the file was not created. Is it possible to save the file manually to the disk when `diskless = TRUE` and `persist = FALSE`?
```
file3 <- "file3.nc"
nc3 <- create.nc(file3, prefill = FALSE, format = "classic",
                 diskless = TRUE, persist	= FALSE)
dim.def.nc(nc3, "station", 5)
dim.def.nc(nc3, "max_string_length", 32)
var.def.nc(nc3, "name", "NC_CHAR", c("max_string_length", "station"))
myname <- c("alfa", "bravo", "charlie", "delta", "echo")
var.put.nc(nc3, "name", myname)
sync.nc(nc3)
close.nc(nc3)
```

Example 4. In comparison with Example 2, two functions (`file.inq.nc()` and `print.nc()`) were called before closing the dataset. The output is also shown below. Does it say anything?
```
file4 <- "file4.nc"
nc4 <- create.nc(file4, prefill = FALSE, format = "classic",
                 diskless = TRUE, persist	= TRUE)
dim.def.nc(nc4, "station", 5)
dim.def.nc(nc4, "max_string_length", 32)
var.def.nc(nc4, "name", "NC_CHAR", c("max_string_length", "station"))
myname <- c("alfa", "bravo", "charlie", "delta", "echo")
var.put.nc(nc4, "name", myname)
file.inq.nc(nc4)
print.nc(nc4)
close.nc(nc4)
```
```
> file.inq.nc(nc4)
#> $ndims
#> [1] 2
#> $nvars
#> [1] 1
#> $ngatts
#> [1] 0
#> $unlimdimid
#> [1] NA
#> $format
#> [1] "classic"
#> $libvers
#> [1] "4.7.4 of Aug 15 2021 19:41:09 $"
```
```
> print.nc(nc4)
#> netcdf classic {
#> dimensions:
#>     station = 5 ;
#>     max_string_length = 32 ;
#> variables:
#>     NC_CHAR name(max_string_length, station) ;
#> }
```

**Comment by mdsumner** [comment]
I see the issue in windows, not in linux

can provide details later if needed

**Comment by mjwoods** [comment]
Thanks @mdsumner . It's good to have confirmation of that.

**Comment by mjwoods** [comment]
Thanks also to @AndreySamokhin for preparing those examples. I suppose `diskless` on its own is useful for temporary files, making them faster and reducing I/O load on the system - and at least that option seems to be working. It helps to know that the combination of `diskless` and `persist` is not working properly, and I will check that it works in newer builds of the netcdf library.

**Comment by mjwoods** [comment]
Hi @AndreySamokhin and @mdsumner , are you still interested in using files with `diskless = TRUE` and `persist = TRUE` on Windows? If so, this appears to work on the upcoming version of RNetCDF_2.5-3, which has been rebuilt with the new netcdf-4.9.0 library for Windows. The new package should appear on CRAN within a week or so.

**Comment by mdsumner** [comment]
I don't actually use the feature, but very happy to see this update roll through - thanks!

**Comment by AndreySamokhin** [comment]
Hi @mjwoods, I've run all examples. It works now. Thank you very much!

**Comment by mjwoods** [comment]
That's great news @AndreySamokhin . Thanks for reporting the problem.
