### ISSUE TITLE
RnetCDF seems to not support compression

### ISSUE THREAD

**Issue by fenclmar** [mjwoods/RNetCDF#98]
I encountered problem with netCDF compression. The package seems to not support it and produces always uncompressed files:

```
library(RNetCDF)
for (dLevel in c(NA, 1:9)) {
  nc <- create.nc(paste0("test_compression_level", dLevel, ".nc"))
  dim.def.nc(nc, "x", 1e2)
  dim.def.nc(nc, "y", 1e2)
  dim.def.nc(nc, "time", unlim=TRUE)
  var.def.nc(nc, "data", "NC_DOUBLE", c("x", "y", "time"), deflate = dLevel,
             shuffle = T)
  att.put.nc(nc, "data", "units", "NC_CHAR", "dB")
  dataNc <- array(rep(1:10, each = 1e4), dim = c(1e2, 1e2, 1e1))
  var.put.nc(nc, 'data', dataNc, start = c(1, 1, 1), count = c(1e2, 1e2, 1e1))
  close.nc(nc)
}
print(file.size(paste0("test_compression_level", c(NA, 1:9), ".nc")))
```

(package version 2.6.1 downloaded from CRAN, R version 4.0.0, run at windows station: Windows 10 Pro, Version 21H1)

**Comment by fenclmar** [comment]
Hi Milton, thanks for an advice. It works for netcd4 also on my windows! I missed that the format is not by default netcd4.

**Comment by mjwoods** [comment]
Thanks @fenclmar, I have updated the help files (#100) to make this clearer.
